apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: roulette
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://roulette-db-rw.roulette.svc.cluster.local:5432/roulette
  SPRING_DATASOURCE_USERNAME: "pesho"
  SPRING_DATASOURCE_PASSWORD: "1234"
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_FLYWAY_ENABLED: "true"