apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: roulette
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://roulette-db-rw.roulette.svc.cluster.local:5432/roulette
  DB_USERNAME: "pesho"
  DB_PASSWORD: "1234"
  JWT_SECRET: dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIHZpcnR1YWwgcm91bGV0dGUgYXBw
  