apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: roulette
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: alex270817/virtual-roulette-backend:v1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15