apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: roulette
data:
  default.conf: |
    server {
      listen 80;

      location /api/ {
        proxy_pass http://backend.roulette.svc.cluster.local/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }