spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #${DB_URL}
    username: postgres  #${DB_USERNAME}
    password: 1234          #${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update #Automatic updates db not suitable for production.
    show-sql: true #Prints sql queries in the console.
    open-in-view: false # Service layer must prepare the data before returning it. No lazy loading in controllers.

  jwt:
    secret:  #${JWT_SECRET}
