spring:
  application:
    name: backend
  
  datasource:
    #Same as docker-compose.yaml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/roulette_db}
    username: ${SPRING_DATASOURCE_USERNAME:pesho}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update #Automatic creattion of tables
